---
title: "midterm"
format: pdf
editor: visual
---

## 

```{r}
library(bayesrules)
library(bayesplot)
library(ggplot2)
library(dplyr)
```

# Section 1

```{r}
x <- 8
n <- 10

compute_posterior <- function(a_prior, b_prior) {
  #compute posteriors for each
  a_post <- a_prior + x
  b_post<- b_prior + n - x
  
  posterior_mean <- a_post/(a_post + b_post)
  #compute by 95% convidence level
  ci <- qbeta(c(0.025, 0.975), a_post, b_post)
  #print results
  cat(sprintf("Prior: Beta(%.1f, %.1f) -> Posterior: Beta(%.1f, %.1f)\n", 
              a_prior, b_prior, a_post, b_post))
  cat(sprintf("  Posterior Mean: %.4f\n", posterior_mean))
  cat(sprintf("  95%% Credible Interval: [%.4f, %.4f]\n\n", ci[1], ci[2]))
}
#author's prior
compute_posterior(0.5,0.5)
#uninformative prior
compute_posterior(1,1)
#sympetric prior
compute_posterior(3,3)
```

```{r}
plot_beta_binomial(alpha = 0.5, beta = 0.5, y = 8, n = 10)
plot_beta_binomial(alpha = 1, beta = 1, y = 8, n = 10)
plot_beta_binomial(alpha = 3, beta = 3, y = 8, n = 10)
```

# Section 2

```{r}
set.seed(417)
N <- 10000

```
